root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["public", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  exclude_regex = ["_test\\.go", "_templ\\.go"]
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true